# Generated by Django 5.1.6 on 2025-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidapp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='androidapp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='androidapp',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='androidapp',
            name='link',
            field=models.CharField(default='http://example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='androidapp',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
