# Generated by Django 5.1.6 on 2025-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0003_app_remove_usertask_app_remove_usertask_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
