# Generated by Django 5.1.6 on 2025-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_app_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
