# Generated by Django 5.1.6 on 2025-03-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0005_remove_app_is_admin_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_manager/static/app_icons/'),
        ),
    ]
