# Generated by Django 5.1.6 on 2025-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0006_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='app_icons/'),
        ),
    ]
