# Generated by Django 5.1.6 on 2025-03-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0007_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
