# Generated by Django 5.1.6 on 2025-03-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='screenshot',
            field=models.ImageField(upload_to='task_screenshots/'),
        ),
    ]
